"""
Digital Twin SCENE POSITION simulation — MAP-02 / MINECAST-02.

=========================================================================
  EVERY COORDINATE THIS MODULE PRODUCES IS INVENTED.

  It is a DIGITAL TWIN DEMONSTRATION position, not a measurement. No GNSS receiver
  exists on either vehicle (`telemetry_ingest.GNSS_EQUIPPED_VEHICLES` is empty and
  `position_gnss` is in `NEVER_FROM_HARDWARE`), and nothing here reads a sensor.

  So a value from this module must NEVER be presented as:
      GNSS / GPS / a fix / physical / surveyed / hardware-derived.

  It is presented as: SIMULATION - DIGITAL TWIN.
=========================================================================

WHERE THE TRUCKS DRIVE (MINECAST-02)

Each truck follows a DEMONSTRATION ROUTE: an explicit polyline of SCENE_METRES
waypoints, read from `SYNQRA_SIH2026-27-HMI/contracts/scene_routes.json`. That file is
GENERATED by the frontend (`scripts/exportSceneRoutes.ts`) from the very corridor
geometry the 3D scene draws (`minecast/haulRoads.ts`), so a truck here drives on the
roads the scene renders - and the routes carry the corridors' own disclosure:

    SYNTHETIC OPERATIONAL CORRIDORS · NOT NMDC INFRASTRUCTURE · DEMONSTRATION ROUTE

This module owns NO geometry. It only follows what the frontend exported, so there is one
owner of the road network and no second engine that could disagree with it. A frontend
test fails if the committed JSON is stale.

THE FRAME

    SCENE_METRES    metres east (x) and north (y) of the PUBLISHED EXTENT's south-west
                    corner - the frame `minecast/spatialPosition.ts` defines and the
                    terrain mesh is built in. The consumer samples its own terrain for the
                    vertical, so this module supplies x/y and heading only.

MOTION

Deterministic and continuous in elapsed demo time: progress = start + speed * t, then a
PING_PONG (out and back) or LOOP over the polyline, interpolated between waypoints.
Heading is the tangent of the current segment, flipped by pi on the return leg. No RNG,
no wall clock captured at import, no persisted state: the same t always yields the same
pose, so a test can assert an exact coordinate and a turnaround can be shown continuous.
"""

import json
import math
import os
from typing import Any, Dict, List, Optional, Tuple

#: Frame name. Matches `SpatialFrame` in the frontend's spatial-position contract.
SCENE_FRAME = "SCENE_METRES"

#: What produced these numbers. Never "GNSS", never "HARDWARE".
SCENE_METHOD = "DIGITAL_TWIN_SCENE_SIM"

#: Operator-facing provenance label. Rendered verbatim by the HMI.
SCENE_PROVENANCE_LABEL = "SIMULATION · DIGITAL TWIN"

SCENE_REASON = (
    "Digital Twin demonstration position in SCENE_METRES from the published extent's "
    "south-west corner, following a synthetic demonstration route on the scene's "
    "invented corridors. Not a GNSS fix, not a measurement, not surveyed, and not an "
    "NMDC haul road."
)

#: The exported route contract. Generated by the frontend; never hand-edited here.
ROUTES_PATH = os.path.join(
    os.path.dirname(os.path.abspath(__file__)),
    "SYNQRA_SIH2026-27-HMI", "contracts", "scene_routes.json",
)


class _Route:
    """One truck's demonstration route, with cumulative lengths precomputed once."""

    __slots__ = (
        "route_id", "vehicle_id", "behaviour", "speed_mps", "start_progress_m",
        "corridor_ids", "waypoints", "cumulative", "length_m",
    )

    def __init__(self, raw: Dict[str, Any]) -> None:
        self.route_id: str = raw["route_id"]
        self.vehicle_id: str = raw["vehicle_id"]
        self.behaviour: str = raw["behaviour"]
        self.speed_mps: float = float(raw["speed_mps"])
        self.start_progress_m: float = float(raw["start_progress_m"])
        self.corridor_ids: List[str] = list(raw["corridor_ids"])
        self.waypoints: List[Tuple[float, float]] = [
            (float(p[0]), float(p[1])) for p in raw["waypoints"]
        ]
        if len(self.waypoints) < 2:
            raise ValueError(f"route {self.route_id} needs at least two waypoints")
        if self.behaviour not in ("PING_PONG", "LOOP"):
            raise ValueError(f"route {self.route_id}: unknown behaviour {self.behaviour}")

        # Cumulative distance to each waypoint. For LOOP the closing segment is appended.
        cumulative = [0.0]
        for (x0, y0), (x1, y1) in zip(self.waypoints, self.waypoints[1:]):
            cumulative.append(cumulative[-1] + math.hypot(x1 - x0, y1 - y0))
        if self.behaviour == "LOOP":
            (x0, y0), (x1, y1) = self.waypoints[-1], self.waypoints[0]
            cumulative.append(cumulative[-1] + math.hypot(x1 - x0, y1 - y0))
        self.cumulative = cumulative
        self.length_m = cumulative[-1]
        if self.length_m <= 0.0:
            raise ValueError(f"route {self.route_id} has zero length")

    def segment_end(self, index: int) -> Tuple[float, float]:
        """The waypoint that ends segment `index`, wrapping for a LOOP's closing segment."""
        return self.waypoints[(index + 1) % len(self.waypoints)]


def _load_routes(path: str = ROUTES_PATH) -> Tuple[Dict[str, _Route], Dict[str, Any]]:
    with open(path, encoding="utf-8") as fh:
        doc = json.load(fh)
    provenance = doc.get("_provenance", {})
    if provenance.get("frame") != SCENE_FRAME:
        raise ValueError(f"{path}: expected frame {SCENE_FRAME}, got {provenance.get('frame')!r}")
    routes = {}
    for raw in doc["routes"]:
        route = _Route(raw)
        if route.vehicle_id in routes:
            raise ValueError(f"{path}: two routes for {route.vehicle_id}")
        routes[route.vehicle_id] = route
    return routes, provenance


_ROUTES, ROUTES_PROVENANCE = _load_routes()

#: The vehicles this demonstration places. Anything else gets no position at all.
DEMO_SCENE_VEHICLES = tuple(_ROUTES.keys())

#: Published-extent span in metres, from the SAME export the routes came from - so the
#: bounds check and the geometry share one source. Positions must stay inside it.
EXTENT_SPAN_X_M = float(ROUTES_PROVENANCE["extent_m"]["width"])
EXTENT_SPAN_Y_M = float(ROUTES_PROVENANCE["extent_m"]["height"])

#: The routes' own disclosure, carried on every pose.
ROUTE_DISCLOSURE = str(ROUTES_PROVENANCE.get("disclosure", "SYNTHETIC_FOR_DEMO"))
# MINE-ROUTES-02: the route classification the geometry owner stamped on the contract.
ROUTE_CLASSIFICATION = str(
    ROUTES_PROVENANCE.get("route_classification", "SYNTHETIC_DIGITAL_TWIN_ROUTE")
)


def _progress(route: _Route, t_s: float) -> Tuple[float, int]:
    """Metres along the polyline at time t, and +1 outbound / -1 on a PING_PONG return."""
    travelled = route.start_progress_m + route.speed_mps * float(t_s)
    length = route.length_m
    if route.behaviour == "LOOP":
        return travelled % length, 1
    period = 2.0 * length
    phase = travelled % period
    if phase <= length:
        return phase, 1
    return period - phase, -1


def _sample(route: _Route, progress_m: float, direction: int) -> Tuple[float, float, float]:
    """Interpolated (x, y) at `progress_m`, and the heading of travel in radians."""
    cumulative = route.cumulative
    # Find the segment containing progress_m. Bisect keeps this O(log n) per call.
    lo, hi = 0, len(cumulative) - 2
    while lo < hi:
        mid = (lo + hi + 1) // 2
        if cumulative[mid] <= progress_m:
            lo = mid
        else:
            hi = mid - 1
    index = lo
    seg_start = route.waypoints[index]
    seg_end = route.segment_end(index)
    seg_len = cumulative[index + 1] - cumulative[index]
    frac = 0.0 if seg_len <= 0.0 else (progress_m - cumulative[index]) / seg_len
    frac = 0.0 if frac < 0.0 else 1.0 if frac > 1.0 else frac

    x = seg_start[0] + (seg_end[0] - seg_start[0]) * frac
    y = seg_start[1] + (seg_end[1] - seg_start[1]) * frac

    heading = math.atan2(seg_end[1] - seg_start[1], seg_end[0] - seg_start[0])
    if direction < 0:
        heading = math.atan2(-math.sin(heading), -math.cos(heading))
    return x, y, heading


def scene_position(vehicle_id: str, t_s: float) -> Optional[Dict[str, Any]]:
    """
    The demo scene pose for one vehicle at demo time `t_s`, or None.

    Returns None for any vehicle without a route - a vehicle the demonstration does not
    place gets NO position, rather than a plausible-looking default. That is the same
    refusal the rest of the position stack makes.
    """
    route = _ROUTES.get(vehicle_id)
    if route is None:
        return None

    progress_m, direction = _progress(route, t_s)
    x, y, heading = _sample(route, progress_m, direction)

    return {
        "x_m": round(x, 3),
        "y_m": round(y, 3),
        "heading_rad": round(heading, 6),
        "frame": SCENE_FRAME,
        "status": "VALID",
        # Both of these say SIMULATION on every path. There is no branch that promotes a
        # scene pose to HARDWARE, because no hardware produces one.
        "source": "SIMULATION",
        "origin": "SIMULATION",
        "provenance_label": SCENE_PROVENANCE_LABEL,
        "method": SCENE_METHOD,
        "reason": SCENE_REASON,
        # MINECAST-02: the route is explicit and inspectable on every pose.
        "route_id": route.route_id,
        "route_classification": ROUTE_CLASSIFICATION,
        "route_disclosure": ROUTE_DISCLOSURE,
        "progress_m": round(progress_m, 3),
        "direction": direction,
    }


def scene_telemetry_fields(vehicle_id: str, t_s: float) -> Dict[str, Any]:
    """
    The scene keys to merge into a SIMULATED telemetry frame, or `{}`.

    Flat keys, because that is what the `/api/telemetry` allowlist carries. The ingestor
    re-assembles them into the canonical `position_scene` payload.
    """
    pose = scene_position(vehicle_id, t_s)
    if pose is None:
        return {}
    return {
        "scene_x_m": pose["x_m"],
        "scene_y_m": pose["y_m"],
        "scene_heading_rad": pose["heading_rad"],
        # MINE-ROUTES-02: which synthetic route, and which way along it.
        "scene_route_id": pose["route_id"],
        "scene_route_direction": pose["direction"],
    }


def route_speed_mps(vehicle_id: str) -> Optional[float]:
    """
    The constant speed (m/s) this vehicle's route is walked at, or None without a route.

    DIGITAL-TWIN-OPERATIONAL-FLOW-01: `_progress()` above computes
    `start_progress_m + speed_mps * t` - there is no acceleration model, so the scene pose
    genuinely advances at this one constant. This is the ONLY correct "simulation speed"
    to publish alongside that pose: it is not a new measurement, not a UI constant, and not
    derived independently - it is the exact parameter that already drives the position, read
    straight out of the loaded route contract. A producer (e.g. `run_live_demo.py`) uses it
    to make a demo's displayed SIMULATION speed agree with how fast the truck actually
    moves, instead of publishing an unrelated number. Always non-negative; direction
    (forward/return) is carried separately on the pose, exactly as a speedometer shows
    magnitude, not sign.
    """
    route = _ROUTES.get(vehicle_id)
    return None if route is None else route.speed_mps


def demo() -> None:
    """Self-check: determinism, motion, bounds, continuity at the turnaround, tangent heading."""
    a1 = scene_position("TRUCK_01", 10.0)
    a2 = scene_position("TRUCK_01", 10.0)
    assert a1 == a2, "scene positions must be deterministic"

    for vehicle_id in DEMO_SCENE_VEHICLES:
        route = _ROUTES[vehicle_id]
        start = scene_position(vehicle_id, 0.0)
        later = scene_position(vehicle_id, 20.0)
        assert start is not None and later is not None
        assert math.dist((start["x_m"], start["y_m"]), (later["x_m"], later["y_m"])) > 10.0

        for step in range(0, 3600, 13):
            pose = scene_position(vehicle_id, float(step))
            assert pose is not None
            assert 0.0 <= pose["x_m"] <= EXTENT_SPAN_X_M, (vehicle_id, step, pose["x_m"])
            assert 0.0 <= pose["y_m"] <= EXTENT_SPAN_Y_M, (vehicle_id, step, pose["y_m"])
            assert pose["source"] == "SIMULATION" and pose["origin"] == "SIMULATION"

        # No teleport at the far end: the pose just before and just after the turnaround
        # are within one small step of each other.
        t_turn = (route.length_m - route.start_progress_m) / route.speed_mps
        before = scene_position(vehicle_id, t_turn - 0.5)
        after = scene_position(vehicle_id, t_turn + 0.5)
        assert before is not None and after is not None
        assert math.dist((before["x_m"], before["y_m"]), (after["x_m"], after["y_m"])) < route.speed_mps * 1.5

    assert scene_position("TRUCK_99", 0.0) is None, "unknown vehicles get no position"
    print("scene_position_sim: OK")


if __name__ == "__main__":
    demo()
